apiVersion: v1
kind: Pod
metadata:
  name: k8-readyness-probe
spec:
  containers:
  - name: k8-readyness-probe
    image: k8-readyness-probe:1.0
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3